# Generated by Django 2.1.3 on 2018-12-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='descripcion',
            new_name='descripcionE',
        ),
    ]
