# Generated by Django 2.1.3 on 2018-12-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181207_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('idS', models.AutoField(primary_key=True, serialize=False)),
                ('fechaS', models.DateField(auto_now=True)),
                ('cantidadS', models.IntegerField()),
                ('detalleS', models.CharField(choices=[('01', 'Venta'), ('02', 'Recarga'), ('03', 'Reparación')], default='01', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cliente')),
            ],
        ),
    ]
