# Generated by Django 2.1.3 on 2018-12-07 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='descripcionE',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccionE',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombreE',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nitE',
            new_name='nit',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefonoE',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='cantidadS',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='cliente',
            new_name='Cliente',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='detalleS',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fechaS',
        ),
        migrations.AddField(
            model_name='servicio',
            name='Fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicio',
            name='Servicio',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Recarga', 'Recarga'), ('Reparación', 'Reparación')], default='01', max_length=20),
        ),
    ]
