# Generated by Django 2.1.3 on 2018-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20181207_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='Comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
