# Generated by Django 2.1.3 on 2018-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20181208_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
