# Generated by Django 2.1.3 on 2018-12-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20181208_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Comentario',
            field=models.CharField(max_length=100),
        ),
    ]
