# Generated by Django 2.1.3 on 2018-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_auto_20181208_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
