# Generated by Django 2.1.3 on 2018-12-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_auto_20181208_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Comentario', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
